site_name: Bhagavad-gita-1972 
pages:
- Front: 'index.md'
- Week1:
    - Day 1:
        - '1': 'wk1/01.md'
        - '2': 'wk1/02.md'
    - Day 2:
        - '3': 'wk1/03.md'
        - '4': 'wk1/04.md'
    - Day 3:
        - '5': 'wk1/05.md'
        - '6': 'wk1/06.md'
    - Day 4:
        - '7': 'wk1/07.md'
        - '8': 'wk1/08.md'
    - Day 5:
        - '9': 'wk1/09.md'
        - '10': 'wk1/10.md'
    - Day 6:
        - '11': 'wk1/11.md'
        - '12': 'wk1/12.md'
    - Day 7:
        - '13': 'wk1/13.md'
        - '14': 'wk1/14.md'

- Week2:
    - Day 1:
        - '15': 'wk2/15.md'
        - '16': 'wk2/16.md'
    - Day 2:
        - '17': 'wk2/17.md'
        - '18': 'wk2/18.md'
    - Day 3:
        - '19': 'wk2/19.md'
        - '20': 'wk2/20.md'
    - Day 4:
        - '21': 'wk2/21.md'
        - '22': 'wk2/22.md'
    - Day 5:
        - '23': 'wk2/23.md'
        - '24': 'wk2/24.md'
    - Day 6:
        - '25': 'wk2/25.md'
        - '26': 'wk2/26.md'
    - Day 7:
        - '27': 'wk2/27.md'
        - '28': 'wk2/28.md'

- Week3:
    - Day 1:
        - '29': 'wk3/29.md'
        - '30': 'wk3/30.md'
    - Day 2:
        - '31': 'wk3/31.md'
        - '32': 'wk3/32.md'
    - Day 3:
        - '33': 'wk3/33.md'
        - '34': 'wk3/34.md'
    - Day 4:
        - '35': 'wk3/35.md'
        - '36': 'wk3/36.md'
    - Day 5:
        - '37': 'wk3/37.md'
        - '38': 'wk3/38.md'
    - Day 6:
        - '39': 'wk3/39.md'
        - '40': 'wk3/40.md'
    - Day 7:
        - '41': 'wk3/41.md'
        - '42': 'wk3/42.md'

- Week4:
    - Day 1:
        - '43': 'wk4/43.md'
        - '44': 'wk4/44.md'
    - Day 2:
        - '45': 'wk4/45.md'
        - '46': 'wk4/46.md'
    - Day 3:
        - '47': 'wk4/47.md'
        - '48': 'wk4/48.md'
    - Day 4:
        - '49': 'wk4/49.md'
        - '50': 'wk4/50.md'
    - Day 5:
        - '51': 'wk4/51.md'
        - '52': 'wk4/52.md'
    - Day 6:
        - '53': 'wk4/53.md'
        - '54': 'wk4/54.md'
    - Day 7:
        - '55': 'wk4/55.md'
        - '56': 'wk4/56.md'

- Week5:
    - Day 1:
        - '57': 'wk5/57.md'
        - '58': 'wk5/58.md'
    - Day 2:
        - '59': 'wk5/59.md'
        - '60': 'wk5/60.md'
    - Day 3:
        - '61': 'wk5/61.md'
        - '62': 'wk5/62.md'
    - Day 4:
        - '63': 'wk5/63.md'
        - '64': 'wk5/64.md'
    - Day 5:
        - '65': 'wk5/65.md'
        - '66': 'wk5/66.md'
    - Day 6:
        - '67': 'wk5/67.md'
        - '68': 'wk5/68.md'
    - Day 7:
        - '69': 'wk5/69.md'
        - '70': 'wk5/70.md'

- Week6:
    - Day 1:
        - '71': 'wk6/71.md'
        - '72': 'wk6/72.md'
    - Day 2:
        - '73': 'wk6/73.md'
        - '74': 'wk6/74.md'
    - Day 3:
        - '75': 'wk6/75.md'
        - '76': 'wk6/76.md'
    - Day 4:
        - '77': 'wk6/77.md'
        - '78': 'wk6/78.md'
    - Day 5:
        - '79': 'wk6/79.md'
        - '80': 'wk6/80.md'
    - Day 6:
        - '81': 'wk6/81.md'
        - '82': 'wk6/82.md'
    - Day 7:
        - '83': 'wk6/83.md'
        - '84': 'wk6/84.md'

- Week7:
    - Day 1:
        - '85': 'wk7/85.md'
        - '86': 'wk7/86.md'
    - Day 2:
        - '87': 'wk7/87.md'
        - '88': 'wk7/88.md'
    - Day 3:
        - '89': 'wk7/89.md'
        - '90': 'wk7/90.md'
    - Day 4:
        - '91': 'wk7/91.md'
        - '92': 'wk7/92.md'
    - Day 5:
        - '93': 'wk7/93.md'
        - '94': 'wk7/94.md'
    - Day 6:
        - '95': 'wk7/95.md'
        - '96': 'wk7/96.md'
    - Day 7:
        - '97': 'wk7/97.md'
        - '98': 'wk7/98.md'

- Week8:
    - Day 1:
        - '99': 'wk8/99.md'
        - '100': 'wk8/100.md'
    - Day 2:
        - '101': 'wk8/101.md'
        - '102': 'wk8/102.md'
    - Day 3:
        - '103': 'wk8/103.md'
        - '104': 'wk8/104.md'
    - Day 4:
        - '105': 'wk8/105.md'
        - '106': 'wk8/106.md'
    - Day 5:
        - '107': 'wk8/107.md'
        - '108': 'wk8/108.md'

theme: material 
