site_name: Bhagavad-gita-1972 
pages:
- Cover: 'index.md'
- Week1: 
    - '1': 'wk1/01.md'
    - '2': 'wk1/02.md'
    - '3': 'wk1/03.md'
    - '4': 'wk1/04.md'
    - '5': 'wk1/05.md'
    - '6': 'wk1/06.md'
    - '7': 'wk1/07.md'
    - '8': 'wk1/08.md'
    - '9': 'wk1/09.md'
    - '10': 'wk1/10.md'
    - '11': 'wk1/11.md'
    - '12': 'wk1/12.md'
    - '13': 'wk1/13.md'
    - '14': 'wk1/14.md'

- Week2:
    - '15': 'wk2/15.md'
    - '16': 'wk2/16.md'
    - '17': 'wk2/17.md'
    - '18': 'wk2/18.md'
    - '19': 'wk2/19.md'
    - '20': 'wk2/20.md'
    - '21': 'wk2/21.md'
    - '22': 'wk2/22.md'
    - '23': 'wk2/23.md'
    - '24': 'wk2/24.md'
    - '25': 'wk2/25.md'
    - '26': 'wk2/26.md'
    - '27': 'wk2/27.md'
    - '28': 'wk2/28.md'

- Week3:
    - '29': 'wk3/29.md'
    - '30': 'wk3/30.md'
    - '31': 'wk3/31.md'
    - '32': 'wk3/32.md'
    - '33': 'wk3/33.md'
    - '34': 'wk3/34.md'
    - '35': 'wk3/35.md'
    - '36': 'wk3/36.md'
    - '37': 'wk3/37.md'
    - '38': 'wk3/38.md'
    - '39': 'wk3/39.md'
    - '40': 'wk3/40.md'
    - '41': 'wk3/41.md'
    - '42': 'wk3/42.md'

- Week4:
    - '43': 'wk4/43.md'
    - '44': 'wk4/44.md'
    - '45': 'wk4/45.md'
    - '46': 'wk4/46.md'
    - '47': 'wk4/47.md'
    - '48': 'wk4/48.md'
    - '49': 'wk4/49.md'
    - '50': 'wk4/50.md'
    - '51': 'wk4/51.md'
    - '52': 'wk4/52.md'
    - '53': 'wk4/53.md'
    - '54': 'wk4/54.md'
    - '55': 'wk4/55.md'
    - '56': 'wk4/56.md'

- Week5:
    - '57': 'wk5/57.md'
    - '58': 'wk5/58.md'
    - '59': 'wk5/59.md'
    - '60': 'wk5/60.md'
    - '61': 'wk5/61.md'
    - '62': 'wk5/62.md'
    - '63': 'wk5/63.md'
    - '64': 'wk5/64.md'
    - '65': 'wk5/65.md'
    - '66': 'wk5/66.md'
    - '67': 'wk5/67.md'
    - '68': 'wk5/68.md'
    - '69': 'wk5/69.md'
    - '70': 'wk5/70.md'

- Week6:
    - '71': 'wk6/71.md'
    - '72': 'wk6/72.md'
    - '73': 'wk6/73.md'
    - '74': 'wk6/74.md'
    - '75': 'wk6/75.md'
    - '76': 'wk6/76.md'
    - '77': 'wk6/77.md'
    - '78': 'wk6/78.md'
    - '79': 'wk6/79.md'
    - '80': 'wk6/80.md'
    - '81': 'wk6/81.md'
    - '82': 'wk6/82.md'
    - '83': 'wk6/83.md'
    - '84': 'wk6/84.md'

- Week7:
    - '85': 'wk7/85.md'
    - '86': 'wk7/86.md'
    - '87': 'wk7/87.md'
    - '88': 'wk7/88.md'
    - '89': 'wk7/89.md'
    - '90': 'wk7/90.md'
    - '91': 'wk7/91.md'
    - '92': 'wk7/92.md'
    - '93': 'wk7/93.md'
    - '94': 'wk7/94.md'
    - '95': 'wk7/95.md'
    - '96': 'wk7/96.md'
    - '97': 'wk7/97.md'
    - '98': 'wk7/98.md'

- Week8:
    - '99': 'wk8/99.md'
    - '100': 'wk8/100.md'
    - '101': 'wk8/101.md'
    - '102': 'wk8/102.md'
    - '103': 'wk8/103.md'
    - '104': 'wk8/104.md'
    - '105': 'wk8/105.md'
    - '106': 'wk8/106.md'
    - '107': 'wk8/107.md'
    - '108': 'wk8/108.md'

theme: cinder 
